/**
 * SubjectChip — pill representing one selected Subject in the QueryBuilder.
 *
 * Shows the subject's icon + label with two affordances: an ``×`` remove
 * button and a ``▾`` disclosure that reveals a provenance panel. The
 * provenance is the investigator's audit trail — it documents which OSM
 * tags the subject expands to, the curated field note, and the OSM-wiki
 * description fetched at build time and shipped as a static snapshot.
 *
 * No network calls at runtime. The wiki content for every curated tag
 * lives in ``frontend/src/lib/taginfoSnapshot.ts``, generated by
 * ``backend/scripts/build_taginfo_snapshot.py``. Re-run the script when
 * the glossary changes.
 */

import { useState } from "react";
import type { Subject } from "@/lib/subjectCatalog";
import type { GlossaryEntry } from "@/lib/tagLibrary.types";
import { TAGINFO_SNAPSHOT, type TaginfoSnapshotEntry } from "@/lib/taginfoSnapshot";

interface Props {
  subject: Subject;
  glossaryEntries: GlossaryEntry[];
  onRemove: () => void;
}

export function SubjectChip({ subject, glossaryEntries, onRemove }: Props) {
  const [expanded, setExpanded] = useState(false);

  const entries = subject.glossaryEntryIds
    .map((id) => glossaryEntries.find((e) => e.id === id))
    .filter((e): e is GlossaryEntry => e !== undefined);

  return (
    <div className="rounded-md border border-[var(--color-line)] bg-[var(--color-surface-raised)]">
      <div className="flex items-center gap-2 px-2.5 py-1.5">
        <span aria-hidden className="text-base leading-none">
          {subject.icon}
        </span>
        <span className="flex-1 truncate text-sm text-[var(--color-ink)]">
          {subject.label}
        </span>
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          aria-expanded={expanded}
          aria-label={
            expanded ? "Hide what this includes" : "Show what this includes"
          }
          className="rounded p-0.5 text-[var(--color-ink-faint)] transition-colors hover:bg-[var(--color-surface-sunken)] hover:text-[var(--color-ink)]"
        >
          <span aria-hidden className="text-[11px] leading-none">
            {expanded ? "▴" : "▾"}
          </span>
        </button>
        <button
          type="button"
          onClick={onRemove}
          aria-label={`Remove ${subject.label}`}
          className="rounded p-0.5 text-[var(--color-ink-faint)] transition-colors hover:bg-[var(--color-surface-sunken)] hover:text-[var(--color-danger)]"
        >
          <span aria-hidden className="text-base leading-none">
            ×
          </span>
        </button>
      </div>

      {expanded && (
        <div className="space-y-3 border-t border-[var(--color-line)] bg-[var(--color-surface-sunken)] px-3 py-2.5">
          <Eyebrow>Places tagged in OSM as</Eyebrow>

          {entries.length === 0 ? (
            <p className="text-[11px] italic text-[var(--color-ink-faint)]">
              Loading tag details…
            </p>
          ) : (
            <ul className="space-y-3">
              {entries.map((entry) => (
                <li key={entry.id}>
                  <EntryRow entry={entry} />
                </li>
              ))}
            </ul>
          )}

          {/* Field note — surfaced once per chip from the FIRST entry, since
              the editorial guidance usually frames the whole subject (e.g.
              "the cleanest indicator of formal detention…"). Showing it
              once at the bottom keeps it from competing with the per-tag
              descriptions above. */}
          {entries.length > 0 && entries[0].field_note && (
            <div
              className="rounded-md border-l-2 border-[var(--color-accent)] px-3 py-2"
              style={{ background: "#fbf6e8" }}
            >
              <p
                className="uppercase text-[var(--color-accent)]"
                style={{ fontSize: "9px", letterSpacing: "0.22em", fontWeight: 600 }}
              >
                Field note
              </p>
              <p className="mt-1 font-[var(--font-display)] text-[12px] italic leading-snug text-[#3a2e1a]">
                {entries[0].field_note}
              </p>
            </div>
          )}

          <p className="text-[11px] text-[var(--color-ink-soft)]">
            <span
              className="uppercase text-[var(--color-ink-faint)]"
              style={{ fontSize: "9px", letterSpacing: "0.2em", fontWeight: 600 }}
            >
              Typical results
            </span>{" "}
            · {subject.typicalResults}
          </p>
        </div>
      )}
    </div>
  );
}

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <p
      className="uppercase text-[var(--color-ink-faint)]"
      style={{ fontSize: "10px", letterSpacing: "0.22em", fontWeight: 600 }}
    >
      {children}
    </p>
  );
}

interface EntryRowProps {
  entry: GlossaryEntry;
}

/** One row of the "Places tagged in OSM as" list. Renders the canonical
 *  ``key=value`` (or ``key=*`` for wildcard entries), a wiki link, and —
 *  if the build-time snapshot has data for this tag — a one-paragraph
 *  description and a couple of related-tag chips for context.
 */
function EntryRow({ entry }: EntryRowProps) {
  const snapshot = lookupSnapshot(entry);
  const wikiUrl =
    snapshot?.wikiUrl ??
    (entry.value
      ? `https://wiki.openstreetmap.org/wiki/Tag:${encodeURIComponent(entry.key)}=${encodeURIComponent(entry.value)}`
      : `https://wiki.openstreetmap.org/wiki/Key:${encodeURIComponent(entry.key)}`);

  return (
    <div>
      <div className="flex items-center gap-2">
        <span className="font-[var(--font-mono)] text-[11px] text-[var(--color-ink)]">
          {entry.key}
          {entry.value !== null ? `=${entry.value}` : "=*"}
        </span>
        <a
          href={wikiUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="text-[10px] text-[var(--color-accent)] hover:underline"
          title="Open the OSM wiki page in a new tab"
        >
          wiki ↗
        </a>
      </div>
      {snapshot?.description && (
        <p className="mt-0.5 text-[11px] leading-relaxed text-[var(--color-ink-soft)]">
          {truncate(snapshot.description, 280)}
        </p>
      )}
      {snapshot && snapshot.relatedTags.length > 0 && (
        <div className="mt-1 flex flex-wrap gap-1">
          {pickRelatedTags(snapshot.relatedTags).map((t) => (
            <span
              key={t}
              className="rounded border border-[var(--color-line)] bg-[var(--color-surface-raised)] px-1.5 py-px font-[var(--font-mono)] text-[10px] text-[var(--color-ink-faint)]"
            >
              {t}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}

function lookupSnapshot(entry: GlossaryEntry): TaginfoSnapshotEntry | null {
  if (entry.value === null) return null;
  return TAGINFO_SNAPSHOT[`${entry.key}=${entry.value}`] ?? null;
}

/** Trim the related-tag list to the most useful subset.
 *
 *  Taginfo's wiki pages sometimes list 20+ related tags including bare
 *  attribute keys like ``name``/``source``/``website`` that don't add
 *  HR-investigative signal. We prefer ``key=value`` style entries (the
 *  "see also: amenity=clinic" kind) and cap at 5 chips so the chip
 *  detail stays scannable.
 */
function pickRelatedTags(all: readonly string[]): string[] {
  const withEquals = all.filter((t) => t.includes("="));
  const list = withEquals.length > 0 ? withEquals : all;
  return list.slice(0, 5);
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd() + "…";
}
