"""Build the comprehensive offline OSM-tag search index for the frontend.

Walks Taginfo's popular keys (those used at least ``KEY_MIN_COUNT`` times
globally on OSM) and, for each one, fetches its top values (those used at
least ``VALUE_MIN_COUNT`` times). The result is a flat array of
``{key, value, count}`` rows the SubjectPicker can substring-search with
zero network calls.

This is **separate from** the curated 45-entry snapshot in
``build_taginfo_snapshot.py``: that one has rich wiki descriptions for
the editorial catalog; this one trades depth for breadth so investigators
can find any common OSM tag (``amenity=bench``, ``man_made=surveillance``,
``leisure=park``, …) by typing a substring of either side of the pair.

Output: ``frontend/src/lib/taginfoIndex.ts``

Usage::

    cd backend
    .venv/bin/python scripts/build_taginfo_index.py

The first run takes several minutes because the Taginfo client
rate-limits at ~1 req/sec and each key needs its own values call.
Cache-warm reruns finish in seconds. Re-run periodically (every few
months) to pick up new popular tags.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.enrichment.taginfo import TaginfoError, get_keys, get_values  # noqa: E402


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "frontend" / "src" / "lib" / "taginfoIndex.ts"

# Tunables. Picked so the resulting index covers every popular tag an
# investigator might type. The 10k key threshold gives ~600–800 keys; 200
# values per key catches the long tail (obscure values used 100+ times
# worldwide). Nothing is filtered by key — even free-text keys like
# ``name`` are included, since their top-200 values are real things the
# user might search for (place names, "Main Street", …).
KEY_MIN_COUNT = 10_000
VALUE_MIN_COUNT = 1_000
VALUES_PER_KEY_LIMIT = 200


async def _values_for(key: str) -> list[dict[str, int | str]]:
    """Fetch values for ``key`` that meet the ``VALUE_MIN_COUNT`` threshold.

    Returns ``{value, count}`` rows; trims string fields, sorts by count
    descending, caps at ``VALUES_PER_KEY_LIMIT``.
    """
    rows = await get_values(key, limit=VALUES_PER_KEY_LIMIT)
    out: list[dict[str, int | str]] = []
    for row in rows:
        value = row.get("value")
        count = row.get("count")
        if not isinstance(value, str) or not value:
            continue
        if not isinstance(count, int) or count < VALUE_MIN_COUNT:
            continue
        out.append({"k": key, "v": value, "c": count})
    return out


async def build_index() -> list[dict[str, int | str]]:
    print(f"Fetching keys with global count >= {KEY_MIN_COUNT:,}…")
    keys = await get_keys(min_count=KEY_MIN_COUNT)
    keys = [k for k in keys if isinstance(k.get("key"), str)]
    total = len(keys)
    print(f"Got {total} keys. Walking values…")

    index: list[dict[str, int | str]] = []
    for i, k in enumerate(keys, start=1):
        key = k["key"]
        if i % 25 == 0 or i == 1:
            print(f"  [{i:>4}/{total}] {key}", flush=True)
        try:
            index.extend(await _values_for(key))
        except TaginfoError as e:
            print(f"  ! {key}: {e}", flush=True)
            continue
    return index


def _emit_ts(index: list[dict[str, int | str]]) -> str:
    """Serialise to a compact TypeScript module.

    Field names are single letters (``k``/``v``/``c``) so the on-the-wire
    size after minification stays small — at ~10k entries the savings
    add up. The exported type aliases the cryptic names back to readable
    properties.
    """
    # Sort for stable diff: alphabetical by key, then descending count.
    index.sort(key=lambda r: (r["k"], -int(r["c"]) if isinstance(r["c"], int) else 0, r["v"]))
    body = json.dumps(index, indent=0, ensure_ascii=False, separators=(",", ":"))
    # Compress further by stripping the array's internal newlines from json's
    # ``indent=0`` (which still emits newlines between elements). Tabs would
    # be nicer but Prettier in the repo doesn't touch generated files.
    body = body.replace("\n", "")

    return (
        "/**\n"
        " * Offline OpenStreetMap tag index.\n"
        " *\n"
        " * Generated by ``backend/scripts/build_taginfo_index.py`` — a\n"
        " * flat list of popular ``key=value`` pairs (those with global\n"
        " * usage count >= 100 under a popular key). Powers the SubjectPicker's\n"
        " * \"All OSM tags\" search without any runtime network call.\n"
        " *\n"
        " * **Do not edit by hand.** Re-run the build script to refresh.\n"
        " */\n"
        "\n"
        "export interface TaginfoIndexEntry {\n"
        "  /** OSM key, e.g. ``amenity``. */\n"
        "  key: string;\n"
        "  /** OSM value, e.g. ``bench``. */\n"
        "  value: string;\n"
        "  /** Global usage count on openstreetmap.org at index time. Used\n"
        "   *  as a popularity tie-breaker when ranking search results. */\n"
        "  count: number;\n"
        "}\n"
        "\n"
        "// Single-letter field names in the JSON keep the bundle smaller;\n"
        "// the wrapper below decodes to readable property names lazily.\n"
        "interface CompactRow { k: string; v: string; c: number }\n"
        "\n"
        f"const RAW: CompactRow[] = {body};\n"
        "\n"
        "export const TAGINFO_INDEX: TaginfoIndexEntry[] = RAW.map(\n"
        "  (r) => ({ key: r.k, value: r.v, count: r.c }),\n"
        ");\n"
    )


def main() -> None:
    print(f"Building Taginfo index → {OUTPUT_PATH}")
    index = asyncio.run(build_index())
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(_emit_ts(index), encoding="utf-8")
    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"Wrote {len(index):,} entries ({size_kb:.0f} KB) → {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
